version: '2'
services:
    jbottlestore-app:
        image: jbottlestore
        external_links:
            - jbottlestore-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/jbottlestore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jbottlestore-mariadb:
        extends:
            file: mariadb.yml
            service: jbottlestore-mariadb
